sonar.projectKey=cibox-rover
sonar.projectName=CIBOX Mars Rover
sonar.sources=.
sonar.tests=tests
sonar.exclusions=.venv/**,**/__pycache__/**,.pytest_cache/**,test-results.xml
sonar.python.version=3.12
