sonar.projectKey=cibox-rover
sonar.projectName=CIBOX Mars Rover

sonar.sources=rover.py
sonar.tests=tests

sonar.test.inclusions=tests/**/*.py
sonar.exclusions=.venv/**,**/__pycache__/**,.pytest_cache/**,test-results.xml

sonar.python.version=3.12
